let artista=[
    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/andrea%20echeverri.webp?alt=media&token=763de34c-6535-47cb-a694-37c38ee92289",historia:'Inició su carrera musical en 1990 como vocalista del grupo "Delia y los Aminoácidos", que desde 1993 pasaría a llamarse Aterciopelados. Durante su exitoso inicio en la música acompañó a Soda Stereo en su MTV Unplugged en el año de 1996, y a partir de ahí fue creciendo paulatinamente como cantante y artista.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Mar%C3%ADa%20Mulata.jpg?alt=media&token=255cf89f-14f6-43ea-95c6-22cea4e7471d",historia:'Hija de la música que, además de sentir como propia la herencia rítmica y cultural de cada rincón de Colombia, es fruto del amor entre dos músicos que ambientaron su infancia con vallenatos, porros, cumbias, guabinas y pasillos. A los 4 años, junto a su hermano, empezó a cantar música andina.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Karol%20G.jpg?alt=media&token=8c8625d9-4b59-402c-93ca-534fd46117c7",historia:'Carolina Giraldo Navarro, mejor conocida como Karol G –un nombre artístico  que resulta una fusión de su apodo y la primera letra de su apellido– es una cantante y compositora colombiana perteneciente a esta nueva ola de representación femenina en el género urbano y clara representante del poder de la mujer latina en el mundo. La cantante cuenta con tres álbumes de estudio desde 2017 a 2019, mismos que le han otorgado 6 nominaciones a los Latin Grammy, ganando en 2018 el reconocimiento de ‘Mejor artista nuevo’; además de varias colaboraciones con destacados artistas latinoamericanos como J Balvin, Anuel AA, Bad Bunny, Camilo y Ozuna.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Shakira.jpg?alt=media&token=7a90d65b-11b8-43a4-bc99-2cd4f6f453f4",historia:'(Shakira Isabel Mebarak Ripoll; Barranquilla, 1977) Cantante colombiana de pop-rock latino. Son muy pocas las estrellas latinoamericanas de la música pop-rock que han logrado un éxito internacional tan fulminante como Shakira, intérprete y compositora en castellano e inglés que ha alcanzado un puesto destacadísimo en los ámbitos de ambas lenguas'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Petrona%20Mart%C3%ADnez.jpg?alt=media&token=f6c017cb-f82c-4046-aced-9f1aac009f72",historia:'Petrona Martínez (San Cayetano, Bolívar, Colombia, 27 de enero de 1939) es una cantadora afrocolombiana de bullerengue, música autóctona de la Costa Caribe de Colombia.Es reconocida por posicionar en circuitos internacionales el bullerengue, música tradicional de mujeres mayores en comunidades rurales afrodescendientes del Caribe colombiano. Petrona Martínez ha tenido una fructífera carrera discográfica como líder del grupo que lleva su nombre. Ha realizado giras por España, Dinamarca, Inglaterra, Francia, Estados Unidos, Marruecos y otros paísesGarcia-Orozco, Manuel. 2016. Petrona Martinez la cantadora que alegra las penas. Mincultura. Sus puntos de mayor reconocimiento a nivel internacional han sido sus tres nominaciones y un gramófono en los premios Grammy por mejor álbum de música latina.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/toto%20la%20momposina.jpg.crdownload?alt=media&token=dfbbd38d-c7a8-48a8-b2ea-e796190eedbe",historia:'Totó La Momposina es una cantante, bailarina y maestra, reconocida internacionalmente por la divulgación de la música folclórica del Caribe colombiano. Nació en Talaigua (Bolívar) en la región geográfica conocida como la depresión momposina, de ahí su nombre artístico. Creció en una familia de músicos, tanto su madre como su padre, fueron grandes impulsores de la música del Caribe, lo que los llevó a conformar un grupo de música con el cual Totó dio a conocer su talento al mundo. Desde la década de 1970 ha recorrido decenas de países interpretando cumbias, porros, mapalés y bullerengues. Hoy en día sigue dedicándose a la música y a la promoción de las tradiciones culturales del Caribe.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Paola%20Jara.jpg?alt=media&token=a7836bd9-d277-494c-a130-1cbf7235531b",historia:'Paola Jara es una artista enfocada en la música popular colombiana y las rancheras.Su nombre real es Paula Andrea Zapata Jaramillo y reside en la ciudad de Medellín, Colombia.Grabó su primer disco a la edad de 14 años, siendo uno de los primeros exponentes femeninos en grabar rancheras.Se dio a conocer como telonera de un concierto de Vicente Fernández y Alejandro Fernández en la ciudad de Medellín. ​ En su carrera musical ha compartido escenario con renombrados artistas colombianos de música popular como Darío Gómez, Marbelle, Jhonny Rivera, Las Hermanas Calle y Helenita Vargas, entre otros; y con artistas internacionales como Vicente Fernández, Alejandro Fernández y Juan Gabriel.En el 2009 lanzó su primera producción discográfica “Paola Jara”, en el año 2014 "Inigualable" y el el año 2019 "En tus manos".'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/Adriana%20Luc%C3%ADa.jpg?alt=media&token=1931cc13-fa53-4a0a-9a14-fe89525d59c4",historia:'Adriana Lucía es cantante de tiempo completo. Su primer álbum le dio un vuelco total a su vida ya que “Enamórate como yo”, el primer sencillo del disco se convirtió en un clásico en las radios y bares de todo el país. La niñez quedaba a un lado por interpretar temas de amores adultos a un público maravillado ante su versatilidad y talentosa voz. Luego vinieron tres discos más: “Destellos de amor”, “Te amaría”, “De corazón a corazón”, hasta llegar a “Porro Nuevo”, un disco soñado pero no planeado, que trabajó de la mano con el cantante samario Carlos Vives, su principal motor e impulsor, y también gestor del más grande cambio de la historia musical reciente de Colombia, junto al productor musical; Andrés Castro.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/atalina%20Garc%C3%ADa.JPG?alt=media&token=a4f8f6db-3760-44c0-bac2-5084ff997658",historia:'Quizás el recuerdo más lejano que Catalina García tenga de su encuentro con la música, es el de su abuelo materno enseñándole a trovar en la finca de Calarcá. Nacida en Cali en febrero de 1986, creció escuchando salsa de noche y de día, herencia de su familia paterna; pero cada fin de semana viajaba con su mamá a visitar al abuelo, que la embelesaba con música vieja de las montañas colombianas, pero también con música clásica, ópera, boleros y hasta flamenco.'},

    {foto:"https://firebasestorage.googleapis.com/v0/b/spotify-f26c5.appspot.com/o/J%20Balvin.webp?alt=media&token=9e1d128d-3bb2-45c8-885b-82c6075f90c5",historia:'José Álvaro Osorio Balvin, quien se conoce como J Balvin, es cantante de música urbana nacido en Colombia. Durante sus estudios secundarios en Medellín formó parte de bandas de rock. Viajó a Estados Unidos en un intercambio cultural. Allí aprendió inglés y conoció el hip hop, estilo que provocaría un giro rotundo en su manera de relacionarse con la música.'}
]
